#name = "fixtweet"
name = "fxtwitter"
account_id = "aad64d6c30ef7796ef8bbacabeceea50"
main = "./dist/worker.js"
compatibility_date = "2024-11-14"
send_metrics = false



[build]
command = "npm run build"
